name: "PR Title Checker"
description: "Checks if the PR Title follows contribution guidelines."
branding:
  icon: 'tag'  
  color: 'purple'
on: [pull_request]
inputs:
  GITHUB_TOKEN:
    required: true
  regex:
    description: "Regular expression to test PR title"
    required: true
  label_name:
    description: "Label that will be given to the project if its name does not match the regular expression"
    required: false
    default: "bad-title"
  label_color:
    description: "Label color"
    required: false
    default: "CCCCCC"
runs:
  using: "node12"
  main: "dist/index.js"
